packageList:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg2
  - software-properties-common
keyUrl:
  - https://download.docker.com/linux/ubuntu/gpg
  - https://packages.cloud.google.com/apt/doc/apt-key.gpg
  - https://baltocdn.com/helm/signing.asc
repoUrl:
  - deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ hostvars[inventory_hostname].ansible_distribution_release }} stable
  - deb https://apt.kubernetes.io/ kubernetes-xenial main
  - deb https://baltocdn.com/helm/stable/debian/ all main
dockerVersion: 5:19.03.13~3-0~ubuntu-bionic
k8sVersion: 1.18.9-00
dockerK8sPackages:
  - docker-ce-cli={{ dockerVersion }}
  - docker-ce={{ dockerVersion }}
  - containerd.io=1.3.7-1
  - kubectl={{ k8sVersion }}
  - kubelet={{ k8sVersion }}
  - kubeadm={{ k8sVersion }}
  - helm
dockerUser: ubuntu
podNetworkCidr: 10.244.0.0/16
k8sApiIf: ens192
cni: calico # calico / flannel / antrea
cniFlannelUrl: https://github.com/coreos/flannel/raw/master/Documentation/kube-flannel.yml
cniCalicoUrl: https://docs.projectcalico.org/manifests/calico.yaml
cniAntreaUrl: kubectl apply -f https://raw.githubusercontent.com/vmware-tanzu/antrea/master/build/yamls/antrea.yml